#name = input("What is your name?\n")
#age = int(input("How old are you?\n"))
#city = input("Where do you live?\n")
#print("Hello,", name, "!")
#print("Your age is", age,":)")
#print("You live in", city,"!")

a = int(input("Enter a: "))
b = int(input("Enter b: "))
print ("I'll show you some magic\n")
print("a+b =", a+b)
print("a-b =", a-b)
print("a*b =", a*b)
print("a/b =", a/b)
print("a**b =", a**b)
